---
- hosts: all
  gather_facts: no
  tasks:
    - name: get system info rpi
      when: inventory_hostname in groups['rpi']
      remote_user: username
      script:
        cmd: ../scripts/system_info.sh
        args:
          creates: /home/username/{{ inventory_hostname }}

    - name: get system info ups
      when: inventory_hostname in groups['ups']
      remote_user: username
      script:
        cmd: ../scripts/system_info.sh
        args:
          creates: /home/username/{{ inventory_hostname }}

    - name: get system info jetson
      when: inventory_hostname in groups['jetson']
      remote_user: username
      script:
        cmd: ../scripts/system_info.sh
        args:
          creates: /home/username/{{ inventory_hostname }}

    - name: fetch result rpi
      when: inventory_hostname in groups['rpi']
      remote_user: username
      fetch:
        src: /home/username/{{ inventory_hostname }}
        dest: ../fetch/
        flat: yes

    - name: fetch result upsquared
      when: inventory_hostname in groups['ups']
      remote_user: username
      fetch:
        src: /home/username/{{ inventory_hostname }}
        dest: ../fetch/
        flat: yes

    - name: fetch result jetson
      when: inventory_hostname in groups['jetson']
      remote_user: username
      fetch:
        src: /home/username/{{ inventory_hostname }}
        dest: ../fetch/
        flat: yes

    - name: merge results
      local_action: shell echo "" > ../reports/system_report && cat ../fetch/* >> ../reports/system_report

